### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by rjkerrison** [rjkerrison/ciaocine#32]
All current information should be available via a REST API.

Conversion of existing info should be relatively simple.

## Tasks

- [x] adding JWT authentication middleware and auth routes
- creating endpoints which serve existing information as JSON
  - [x] movies
  - [x] showtimes filtered by date
  - [x] cinemas
    - GET all
    - GET detail
    - [x] favouriting for authenticated user
  -  [x] calendar for authenticated user
    - post
    - delete
    - read

**Comment by rjkerrison** [comment]
Completed. Lacks documentation but closing for now as a React frontend is now unblocked.
